language: ruby
cache:
  directories:
    - vendor/bundle
    - travis_phantomjs
sudo: false
rvm:
  - "2.3.3"
notifications:
  email: false
bundler_args: --without development:production --deployment --retry=3 --jobs=3
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
before_install:
  - "export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH"
  - if [ $(phantomjs --version) != '2.1.1' ]; then 
      rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs;
      wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2;
      tar -xvf $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; 
    fi
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: bundle exec rake test
addons:
  postgresql: "9.3"
services:
  - redis-server
