language: ruby
cache:
  directories:
    - vendor/bundle
    - travis_phantomjs
    - test/vcr_cassettes
sudo: false
rvm:
  - "2.4.1"
notifications:
  email: false
bundler_args: --without development:production --deployment --retry=3 --jobs=3
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake assets:precompile &> /dev/null
before_install:
  - "export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH"
  - if [ $(phantomjs --version) != '2.1.1' ]; then
      rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs;
      wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2;
      tar -xvf $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs;
    fi
  - "export DISPLAY=:99.0"
  - gem install bundler:1.17.3
script:
  - bundle exec rubocop
  - bundle exec rake test
after_success:
  - if [[ "$TRAVIS_BRANCH" = "production" && "$TRAVIS_EVENT_TYPE" = "push" ]]; then
      openssl aes-256-cbc -K $encrypted_e5503b6e115e_key -iv $encrypted_e5503b6e115e_iv
        -in deploy/deploy_rsa.enc -out /tmp/deploy_rsa -d;

      eval "$(ssh-agent -s)";
      chmod 600 /tmp/deploy_rsa;
      ssh-add /tmp/deploy_rsa;

      echo "\\nDeploying in progress ...";
      ssh -o StrictHostKeyChecking=no root@$DEPLOY_HOST "exec &> deploy.log && ./deploy";
      echo "\\nDeploy finished! Check deploy logs on server.";
    fi
addons:
  postgresql: "9.3"
  apt:
    packages:
      - postgresql-9.3
      - postgresql-client-9.3
      - postgresql-contrib-9.3
services:
  - redis-server
  - xvfb
env:
  global:
    - PGPORT=5433
