version: "3"
services:
  app:
    build: .
    command: unicorn -c config/unicorn.rb 
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - postgres
      - redis

  postgres:
    image: postgres:9.6

  redis:
    image: redis:3.2


