shared: &shared
  forum_url: 'http://community.rubybench.org'

test:
  <<: *shared

development:
  # change to match your local discourse instance
  forum_url: 'http://l.discourse'

production:
  <<: *shared
